//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string username { get; set; }
        public string password { get; set; }
        public string cart { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string website { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string job { get; set; }
        public string image { get; set; }
        public string role { get; set; }
    }
}
