//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class hoadon
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Payment { get; set; }
        public string Shipping { get; set; }
        public string OrderCart { get; set; }
        public Nullable<double> Total { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Custom { get; set; }

        [NotMapped]
        public List<string> Orders  = new List<string>();   
    }
}
