//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mypham
    {
        public int ID { get; set; }
        public string TenMP { get; set; }
        public string MoTa { get; set; }
        public int SoLuong { get; set; }
        public int DaBan { get; set; }
        public double GiaGoc { get; set; }
        public double GiaSale { get; set; }
        public string ImageLists { get; set; }
        public string ImageTitle { get; set; }
        public Nullable<int> TheLoai { get; set; }
        public string type { get; set; }
    }
}
